baseURL = 'https://suha-academy.github.io/paattu-pusthakam'
languageCode = 'ta'
title = 'பாட்டு புஸ்தகம்'
theme = ['vortisil']

[taxonomies]
  author = 'author'
  category = 'categories'
  tag = 'tags'

defaultContentLanguage = "ta"
defaultContentLanguageInSubdir = true
disableDefaultLanguageRedirect = false

[[languages.ta.menus.main]]
    identifier = "home"
    url = "/ta"
    weight = 1

[[languages.ta.menus.main]]
    identifier = "about"
    url = "/ta/about"
    weight = 2

[[languages.ta.menus.main]]
    identifier = "songs"
    url = "/ta/songs"
    weight = 3

[[languages.ta.menus.main]]
    identifier = "search"
    url = "/ta/search"
    weight = 4

[[languages.en.menus.main]]
    identifier = "home"
    url = "/en"
    weight = 1

[[languages.en.menus.main]]
    identifier = "about"
    url = "/en/about"
    weight = 2

[[languages.en.menus.main]]
    identifier = "songs"
    url = "/en/songs"
    weight = 3

[[languages.en.menus.main]]
    identifier = "search"
    url = "/en/search"
    weight = 4

[languages]
[languages.ta]
  languageName = "தமிழ்"
  contentDir = 'content/ta'
  disabled = false
  weight = 1
[languages.en]
  languageName = "English"
  contentDir = 'content/en'
  disabled = false
  weight = 2

[outputs]
    home = ["HTML", "JSON"]
